language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

install:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
