name: Test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
        version:
          - 'stable'
          - 'lowest'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer update --prefer-${{ matrix.version }} --prefer-dist --no-interaction --no-suggest

      - name: Run test
        run: ./vendor/bin/phpunit --coverage-clover ./coverage.xml

      - uses: codecov/codecov-action@v1
        with:
          flags: unittests
          fail_ci_if_error: true
